### ISSUE TITLE
combine SVM and LogisticRegression

### ISSUE THREAD

**Issue by affogato** [ProjectAGI/agi#14]

**Comment by nadgeri14** [comment]
hey could I work on it ?

**Comment by affogato** [comment]
Hi @nadgeri14 thanks for the interest. This is outdated, I will close it. We've started using Tensorflow instead and writing a lot of code in Python. If you're interested in getting involved, keep in touch. We're soon to publish another newer codebase that will have a lot of scope for new features!

**Comment by nadgeri14** [comment]
Hey @affogato !! Thanks for the reply. I would like to start contributing to the new code base. Could you notify me when the new code base will be available?

**Comment by affogato** [comment]
Sure!!!
