### ISSUE TITLE
Couldn't find reading materials and architectural descriptions

### ISSUE THREAD

**Issue by misgeatgit** [ProjectAGI/agi#25]
Are there any readme docs for a general understanding of what the code does? also some architectural diagrams?

**Comment by misgeatgit** [comment]
Are there any readme docs for a general understanding of what the code does? also some architectural diagrams?

**Comment by affogato** [comment]
Hi Misgana, there certainly is. If you go to the agi repository, there is a
README in the root folder. It should come up on github if you scroll down.

It also refers to a wiki with more information.

Start from AGI. That should be all you need for now.

I'm working on an architectural diagram as well.

Gideon Kowadlo, Ph.D.
http://gideon.kowadlo.net
@gidsy

Project AGI
http://agi.io
@ProjectAGI

**Comment by affogato** [comment]
and we'll have some more 'getting started' docs for creating a demo, but
there are many demo examples (not so simple) you can look at now

Gideon Kowadlo, Ph.D.
http://gideon.kowadlo.net
@gidsy

Project AGI
http://agi.io
@ProjectAGI

**Comment by affogato** [comment]
Hi Misgana, the README and Wiki have been updated and extended. There is now a diagram referred to in the wiki. Take a look and let me know if you have any questions.
Regards
